# Generated by Django 4.1 on 2022-08-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonacci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Fibonacci name')),
                ('about', models.TextField(verbose_name='Fibonacci about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Fibonacci image')),
            ],
        ),
    ]
